#!/bin/bash -e

Local=$1
Remote=$2

if [[ ! -d "$Local" || ! -d "$Remote" ]]; then
    echo "Error: nvim_difftool expects directories (use git difftool -d)" >&2
    exit 1
fi

TmpDir=$(mktemp -d /tmp/nvim_difftool.XXXXXX)
LocalCopy="$TmpDir/left"
RemoteCopy="$TmpDir/right"
cp -r "$Local" "$LocalCopy"
cp -r "$Remote" "$RemoteCopy"
WorkTree=$(git rev-parse --show-toplevel)

DiffToolCmd="DiffTool $LocalCopy $RemoteCopy"
SetTmpDir="let t:difftool_tmp_dir='$TmpDir'"
SetWorkTree="let t:difftool_work_tree='$WorkTree'"

if [[ -n "$NVIM" ]]; then
    echo "$LocalCopy"
    nvr -cc "if mode()=='t' | let b:LeftInTerminalMode=1 | endif" \
        -cc "lua CloseDiffTool()" \
        -cc "tabnew" \
        -cc "$SetTmpDir" \
        -cc "$SetWorkTree" \
        -cc "$DiffToolCmd"
else
    nvim -c "$SetTmpDir" -c "$SetWorkTree" -c "$DiffToolCmd"
fi
